### ISSUE TITLE
Thanks for this, but.

### ISSUE THREAD

**Issue by Lannebro** [manups4e/esx_eden_garage#1]
When people buy the cars it goes directly to the impound, not linking with garage. They need to pay the impound before its accessable or mod it. Any fix for this? Thx

**Comment by manups4e** [comment]
It might be a vehicleshop error since to me everything works

Il Gio 2 Ago 2018, 13:52 Lannebro <notifications@github.com> ha scritto:

**Comment by Lannebro** [comment]
Hmm thats weird. Running newest version of vehicleshop. Hm..

**Comment by manups4e** [comment]
Did u use ESX migrate?

**Comment by Lannebro** [comment]
Instead of using migrate i reset the db. Clear installs of cardealer, lscustom and garage.. When buying, and they turn it in the garage for the first time, it tells them the car is already out. They cant get it out again untill restart or i manually change the state on the car in db. After restart the car is working correctly with garage, impund and lscustoms. Huge problem for me, and dont know why if its only happening to me.

**Comment by manups4e** [comment]
Did you try drp garage?

**Comment by Lannebro** [comment]
You on discord? Maybe its easyer to talk.

**Comment by manups4e** [comment]
I'm not home^^

**Comment by Lannebro** [comment]
Okey, never tried dpr garage. Is it better?

**Comment by manups4e** [comment]
It's the same but from another one.. look in fx_scripts

**Comment by Lannebro** [comment]
Okey, trying it now =)

**Comment by Lannebro** [comment]
Same thing. Buy from cardealer. Turns it in the garage, try to take it out. ( Car is impounded)

**Comment by manups4e** [comment]
I don't know how to help you then^^

Il Mar 7 Ago 2018, 11:00 Lannebro <notifications@github.com> ha scritto:

**Comment by Lannebro** [comment]
Hmm, i think its the cardealer. If i go as dealer. Give car, it gives 6 numbers vehicleplate for me. But the buyer sees the originalnumbers. When he is trying to give it to garage it turns in a original number. I think thats why it cant turn it in. After restart. That car gets the 6 digitnumbers. Fault most be within the car dealer. Must ppl buy there own cars? I do think that would fix the issue. But ofc u would want dealers.

**Comment by Lannebro** [comment]
Esx migrate is just for transforming old database right? I dont need it if i have clear install?

**Comment by manups4e** [comment]
Nope

Il Mar 7 Ago 2018, 11:13 Lannebro <notifications@github.com> ha scritto:

**Comment by Lannebro** [comment]
I made a comment on esx_cardealer. The problem is 100% there.

**Comment by twistedcinema** [comment]
You solve this yet?  I am having the same issue with every single eden garage out here.
